### ISSUE TITLE
Sorry .. offtopic but cant contact you otherwise

### ISSUE THREAD

**Issue by sense-amr** [wiebow/d81writer#1]
Hey .. i saw your work on tetris and see you are capable of programming assembly for c64.. just wondering if you had any interest at all .. in making a port for .. ORCA .. for c64.. 

https://github.com/hundredrabbits/Orca

would love to see this on a 64.. 
there is actually an Orca-C version which might be easier to port ? .. 
https://github.com/hundredrabbits/Orca-c

anyway hope to hear from you .. 

great work :)

respect..

**Comment by wiebow** [comment]
I don't know C and to be honest, I'm not interested in this at all, so I have to say no.
